name: Laravel meta package CI

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.3, 7.4, "8.0", 8.1]
        laravel: [8, 9]
        exclude:
          - php: 7.3
            laravel: 9
          - php: 7.4
            laravel: 9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none
      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction --no-progress --ignore-platform-reqs
          composer require "illuminate/support=^${{ matrix.laravel }}"  "illuminate/database=^${{ matrix.laravel }}" 
          composer update --prefer-dist --no-interaction --no-progress --ignore-platform-reqs
      - name: Execute tests
        run: vendor/bin/phpunit --verbose
