name: Laravel meta package CI

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8, "8.1"]
        laravel: [8, 9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none
      - name: install dependencies
        run: |
          composer update 
          composer require "laravel/framework":"^${{ matrix.laravel }}"
          composer update --prefer-dist --no-interaction --no-progress --ignore-platform-reqs
      - name: Execute tests
        run: vendor/bin/phpunit --verbose
